/**
 * HTML Dashboard Generator — uses Gemini to produce level-aware dashboards.
 */

import { GeminiService } from './gemini.js';
import type { UserLevel } from './level-detector.js';

export interface ScoredPool {
  protocol: string;
  pool_name: string;
  category: string;
  tokens: string[];
  tvl_usd: number;
  apy_total: number | null;
  risk_score: number;
  opp_score: number;
}

function formatTvl(usd: number): string {
  if (usd >= 1e9) return `$${(usd / 1e9).toFixed(2)}B`;
  if (usd >= 1e6) return `$${(usd / 1e6).toFixed(2)}M`;
  if (usd >= 1e3) return `$${(usd / 1e3).toFixed(1)}K`;
  return `$${usd.toFixed(0)}`;
}

function riskBadge(score: number): string {
  if (score < 25) return '🟢 Safe';
  if (score < 50) return '🟡 Moderate';
  return '🔴 High Risk';
}

function buildNewbiePrompt(pools: ScoredPool[], userRequest: string): string {
  const top3 = pools.slice(0, 3);
  const poolData = top3.map((p, i) => ({
    rank: i + 1,
    protocol: p.protocol,
    pool: p.pool_name,
    apy: p.apy_total?.toFixed(2) ?? '0',
    apyPer1k: p.apy_total != null ? ((p.apy_total / 100) * 1000).toFixed(2) : '0',
    tvl: formatTvl(p.tvl_usd),
    risk: riskBadge(p.risk_score),
    tokens: p.tokens.join(', '),
  }));

  return `Generate a complete self-contained HTML page for a DeFi yield dashboard aimed at BEGINNERS.
User request: "${userRequest}"

Pool data (top 3 safe pools):
${JSON.stringify(poolData, null, 2)}

Design rules:
- Include <script src="https://cdn.tailwindcss.com"></script> in <head>
- Large friendly cards (rounded-2xl), min font size 18px
- Soft pastel background: bg-blue-50
- Show APY as "$X per year on $1,000" (use apyPer1k)
- Large emoji risk badges (🟢🟡🔴) with plain-language sentence
- NO tables, NO small fonts, NO jargon
- Add a "How to Start in 3 Steps" section at the bottom
- Footer: "Generated by OpenClaw • ${new Date().toUTCString()}"
- Friendly, encouraging tone
- Return raw HTML only — no markdown fences, no explanation`;
}

function buildIntermediatePrompt(pools: ScoredPool[], userRequest: string): string {
  const top8 = pools.slice(0, 8);
  const poolData = top8.map((p, i) => ({
    rank: i + 1,
    protocol: p.protocol,
    pool: p.pool_name,
    category: p.category,
    tokens: p.tokens.join(', '),
    apy: p.apy_total?.toFixed(2) ?? 'N/A',
    tvl: formatTvl(p.tvl_usd),
    oppScore: p.opp_score.toFixed(1),
    risk: riskBadge(p.risk_score),
  }));
  const chartLabels = top8.map((p) => p.protocol);
  const chartData = top8.map((p) => p.apy_total?.toFixed(2) ?? 0);

  return `Generate a complete self-contained HTML page for a DeFi yield dashboard for INTERMEDIATE users.
User request: "${userRequest}"

Pool data (top 8 pools):
${JSON.stringify(poolData, null, 2)}

Chart labels: ${JSON.stringify(chartLabels)}
Chart APY data: ${JSON.stringify(chartData)}

Design rules:
- Include <script src="https://cdn.tailwindcss.com"></script> and <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> in <head>
- Dark professional theme: bg-gray-900 text-white
- 2-column card grid (grid-cols-2 on desktop, grid-cols-1 on mobile)
- Each card shows: protocol, pool name, APY%, TVL, risk badge (🟢🟡🔴), opportunity score
- Add a Chart.js bar chart comparing APYs across protocols using the chart data above
- Chart canvas id="apyChart"
- Footer: "Generated by OpenClaw • ${new Date().toUTCString()}"
- Return raw HTML only — no markdown fences, no explanation`;
}

function buildAdvancedPrompt(pools: ScoredPool[], userRequest: string): string {
  const poolData = pools.slice(0, 20).map((p, i) => ({
    rank: i + 1,
    protocol: p.protocol,
    pool: p.pool_name,
    category: p.category,
    tokens: p.tokens.join('/'),
    apy: p.apy_total?.toFixed(2) ?? 'N/A',
    tvl: formatTvl(p.tvl_usd),
    oppScore: p.opp_score.toFixed(1),
    riskScore: p.risk_score.toFixed(0),
  }));
  const chartLabels = pools.slice(0, 10).map((p) => p.protocol);
  const chartData = pools.slice(0, 10).map((p) => p.apy_total?.toFixed(2) ?? 0);

  return `Generate a complete self-contained HTML page for a DeFi yield dashboard for ADVANCED users.
User request: "${userRequest}"

Pool data:
${JSON.stringify(poolData, null, 2)}

Chart labels: ${JSON.stringify(chartLabels)}
Chart APY data: ${JSON.stringify(chartData)}

Design rules:
- Include <script src="https://cdn.tailwindcss.com"></script> and <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> in <head>
- Dark monospace theme: background #0d1117, color #e6edf3, font-family monospace
- Dense sortable data table: columns Protocol | Pool | Category | APY% | TVL | Opp Score | Risk Score
- Sortable columns: clicking <th> sorts the table (vanilla JS)
- Chart.js line chart (type:'line') for APY comparison using chart data, canvas id="apyChart"
- JSON export button: downloads raw pool data as JSON file
- Sticky table headers
- All data in compact, professional layout
- Footer: "Generated by OpenClaw • ${new Date().toUTCString()}"
- Include the raw pool JSON as a const DATA variable in a <script> block for the export feature
- Return raw HTML only — no markdown fences, no explanation`;
}

export async function generateDashboardHTML(
  pools: ScoredPool[],
  level: UserLevel,
  userRequest: string
): Promise<string> {
  let prompt: string;

  if (level === 'newbie') {
    prompt = buildNewbiePrompt(pools, userRequest);
  } else if (level === 'advanced') {
    prompt = buildAdvancedPrompt(pools, userRequest);
  } else {
    prompt = buildIntermediatePrompt(pools, userRequest);
  }

  const html = await GeminiService.generate(prompt);

  // Strip markdown fences if Gemini wraps the output
  return html
    .replace(/^```html\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/\s*```\s*$/, '')
    .trim();
}
